baseurl = "/"
languageCode = "en-us"
title = "Learn Finite Elements"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

# This defines the menu
# ---------------------
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Practical Finite Elements"
    url = "/practicalFE/"
    weight = 2

[[menu.main]]
    name = "CalculiX Tutorials"
    url = "/CCXTutorials/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

# ---------------------



# This is a footer that will appear on every page
[params]
    description = "A website to learn finite elements"
    footer = "&copy; Kedar A. Malusare, 2022 | [LinkedIn](https://www.linkedin.com/in/kedarmalusare/) | [Github](https://github.com/kedarzc)"
